### ISSUE TITLE
Rollapp panic when sends old blocks

### ISSUE THREAD

**Issue by anhductn2001** [dymensionxyz/dymint#1092] opened 2024-09-25 15:40 UTC
ref: https://github.com/dymensionxyz/e2e-tests/actions/runs/11034444699/job/30648063885?pr=397
logs:
``` 
2024-09-25` 22:19:38 time="Sep 25 15:19:38.420" level=info msg="Block created.[height 168 num_tx 0]" module=block_manager
2024-09-25 22:19:38 time="Sep 25 15:19:38.420" level=debug msg="Applying block[height 168 source produced]" module=block_manager
2024-09-25 22:19:38 time="Sep 25 15:19:38.428" level=error msg="Find the validator for this block. Reward not allocated.[addr 374904677494BA000CEF006E9BF6D17816DDE0E9]" module=x/distribution
2024-09-25 22:19:38 time="Sep 25 15:19:38.435" level=info msg="commit synced[commit 436F6D6D697449447B5B3235352032333720313838203420313538203838203234332031323520323034203139312037382031363620373320333120323720323030203133382032313320313137203231322032353420363620393020323032203235332031383220343920353820313738203639203430203131395D3A41387D]"
2024-09-25 22:19:38 time="Sep 25 15:19:38.435" level=debug msg="snapshot is skipped[height 168]"
2024-09-25 22:19:38 time="Sep 25 15:19:38.436" level=info msg="Gossipping block[height 168]" module=block_manager
2024-09-25 22:19:38 time="Sep 25 15:19:38.436" level=debug msg="Gossiping block.[len 761]" module=p2p
2024-09-25 22:19:38 time="Sep 25 15:19:38.436" level=info msg="Produced empty block.[]" module=block_manager
2024-09-25 22:19:38 time="Sep 25 15:19:38.436" level=info msg="New block.[size 546]" module=block_manager
2024-09-25 22:19:38 time="Sep 25 15:19:38.436" level=debug msg="Added bytes produced to bytes pending submission counter.[bytes added 755 pending 24923]" module=block_manager
2024-09-25 22:19:38 time="Sep 25 15:19:38.437" level=debug msg="indexed block[height 168]" module=txindex
2024-09-25 22:19:38 time="Sep 25 15:19:38.438" level=debug msg="indexed block txs[height 168 num_txs 0]" module=txindex
2024-09-25 22:19:40 time="Sep 25 15:19:40.214" level=info msg="Created batch.[start height 136 end height 168 size 24366 last batch false]" module=block_manager
2024-09-25 22:19:40 time="Sep 25 15:19:40.214" level=debug msg="Submitting batch to DA layer[start height 136 end height 167 da height 72]" module=mock
2024-09-25 22:19:40 time="Sep 25 15:19:40.217" level=info msg="Submitted batch to DA.[start height 136 end height 167]" module=block_manager
2024-09-25 22:19:40 time="Sep 25 15:19:40.266" level=debug msg="Batch already accepted[err create and submit batch: submit batch: sl client submit batch: start height: 136: end height: 167: broadcast batch: broadcast tx: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: expected height (153), but received (136): start-height does not match rollapps state [dymensionxyz/dymension/v3/x/rollapp/keeper/msg_server_update_state.go:77] With gas wanted: '18446744073709551615' and gas used: '307768' : unknown request: already exists pending 24923]" module=block_manager
2024-09-25 22:19:40 panic: create and submit batch: submit batch: sl client submit batch: start height: 136: end height: 167: broadcast batch: broadcast tx: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: expected height (153), but received (136): start-height does not match rollapps state [dymensionxyz/dymension/v3/x/rollapp/keeper/msg_server_update_state.go:77] With gas wanted: '18446744073709551615' and gas used: '307768' : unknown request: already exists

**Comment by omritoptix** [comment] 2024-09-29 11:58
I blv this is to a hub bug of num blocks. @srene can we close this?

**Comment by omritoptix** [comment] 2024-10-02 08:05
closing this as caused by depreacting num blocks on the hub and we reverted it

**Closed by omritoptix** 2024-10-02 08:05 UTC
