### ISSUE TITLE
Rollapp Misbehavior detection and generation - Research

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#565] opened 2024-01-21 20:17 UTC

**Comment by omritoptix** [comment] 2024-08-01 11:20
related work: https://www.notion.so/dymension/Permissionless-Technical-Interaction-Matrix-9fd321353d66451d90940ca84563e72c?pvs=4

**Comment by danwt** [comment] 2024-08-01 15:44
dupe of https://github.com/dymensionxyz/research/issues/215

**Closed by danwt** 2024-08-01 15:44 UTC
