### ISSUE TITLE
dymint adaptive state update

### ISSUE THREAD

**Issue by liorzilp** [dymensionxyz/dymint#302] opened 2023-04-22 16:18 UTC
## Overview

There are situations (due to error scenarios) where the rollapp doesn't manage to commit a state update. 
Such cases might lead to a large gap between the rollapp latest height and the hub's known high.

## Problem
When this gap is created the IBC connection between the hub and the rollapp is not functioning and, packets timeouts and even to an expired state.

## Solution
These scenarios are handled manually and might be monitored (see https://github.com/dymensionxyz/devops/issues/94).
This can't be a long-term solution. The sequencer should detect if a gap exists and automatically increase the updating rate and batch size to the maximum.

**Comment by omritoptix** [comment] 2023-05-03 13:02
duplicate of #306

**Closed by omritoptix** 2023-05-03 13:02 UTC
Labels: C:block batch
